import { PixelPanel } from '@chicken-village/ui';
import { Link } from 'react-router-dom';

export function SettingsPage({ dark, reduced, onDark, onReduced, mode, storageMode, isAdmin, adminUsername, onAdminSignOut, online, unsyncedCount, onSync, syncMode, syncError }: { dark: boolean; reduced: boolean; onDark: (value: boolean) => void; onReduced: (value: boolean) => void; mode: string; storageMode: 'native-sqlite' | 'web-cache'; isAdmin: boolean; adminUsername: string | null; onAdminSignOut: () => Promise<void>; online: boolean; unsyncedCount: number; onSync: () => void; syncMode: 'idle' | 'syncing' | 'local-demo' | 'cloud' | 'error'; syncError: string | null }) {
  return (
    <div className="page settings-page"><header className="page-title"><p className="eyebrow">偏好與資料狀態</p><h1>設定</h1></header>
      <PixelPanel title="顯示"><Toggle label="深色模式" checked={dark} onChange={onDark} /><Toggle label="減少動畫" checked={reduced} onChange={onReduced} /></PixelPanel>
      <PixelPanel title="資料與離線"><div className="setting-row"><span><strong>公開行情</strong><small>農業部 Open Data；失敗時使用已驗證快照</small></span><b>{mode === 'live' ? '正式來源' : '快照'}</b></div><div className="setting-row"><span><strong>公開雞舍</strong><small>Firestore 公開唯讀；管理員寫入</small></span><b>Firebase</b></div><div className="setting-row"><span><strong>本機快取</strong><small>iOS／Android：加密 SQLite；Web：可重建 IndexedDB 快取</small></span><b>{storageMode === 'native-sqlite' ? '加密 SQLite' : 'Web 快取'}</b></div>{isAdmin && <div className="setting-row"><span><strong>同步佇列</strong><small>{syncError ?? (online ? syncMode === 'cloud' ? '最近一次已由 SQL Connect 同步' : syncMode === 'local-demo' ? '本機示範同步' : '可將待處理操作送往伺服器' : '離線中')}</small></span><button type="button" className="secondary-button compact" disabled={!online || unsyncedCount === 0 || syncMode === 'syncing'} onClick={onSync}>{syncMode === 'syncing' ? '同步中…' : unsyncedCount ? `同步 ${unsyncedCount} 筆` : '已同步'}</button></div>}<div className="setting-row"><span><strong>Firebase SQL Connect</strong><small>本機 schema／emulator 已準備；production 尚未部署</small></span><b>未部署</b></div></PixelPanel>
      <PixelPanel title="管理員"><div className="setting-row"><span><strong>{isAdmin ? adminUsername : '管理介面'}</strong><small>{isAdmin ? '已取得雞舍資料維護權限' : '一般使用者不需要登入；只有管理操作需要驗證'}</small></span>{isAdmin ? <button type="button" className="text-button" onClick={() => { void onAdminSignOut(); }}>登出</button> : <Link className="secondary-button compact" to="/admin">管理員登入</Link>}</div></PixelPanel>
      <PixelPanel title="安全"><ul className="notes-list"><li>管理員密碼只由 Firebase Authentication 驗證，不寫入原始碼。</li><li>財務衝突不會自動覆蓋。</li><li>App Check 正式強制前會先監控驗證。</li><li>Firestore 目前使用 Spark 免費方案，正式規則預設拒絕未授權寫入。</li></ul></PixelPanel>
    </div>
  );
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><i /></label>; }
